IMPORTING LIBRARIES

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import requests
from bs4 import BeautifulSoup

import json
from pathlib import Path

THE URL

In [8]:
API_URL = "https://jsonplaceholder.typicode.com/users"

Retrieve customer data with Requests

In [9]:
def get_customers(url) -> list[dict]:
    try:
        response = requests.get(url, timeout=10.0)
        customer_info = response.json()
        return customer_info
    except requests.exceptions.ConnectionError:
        print("Network error. Unable to connect to the server.")

customer_info = get_customers(API_URL)
customer_info  
#print(type(customer_info))

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

Explore nested dictionaries and lists

In [10]:
def explore(record, indent=0):
    for key, value in record.items():
        print("  " * indent + f"- {key}: {type(value).__name__}")
        
        if isinstance(value, dict):
            explore(value, indent + 1)

explore(customer_info[0])

- id: int
- name: str
- username: str
- email: str
- address: dict
  - street: str
  - suite: str
  - city: str
  - zipcode: str
  - geo: dict
    - lat: str
    - lng: str
- phone: str
- website: str
- company: dict
  - name: str
  - catchPhrase: str
  - bs: str

Extract customer attributes

In [11]:
def extract_attributes(customer_info):
    customers_data = []
    
    for item in customer_info:
        
        record = {
            "id": item["id"],
            "name": item["name"],
            "username": item["username"],
            "email": item["email"],
            "email_domain":item["email"].split("@")[1],
            "phone": item["phone"],
            "city": item["address"]["city"],
            "zipcode": item["address"]["zipcode"],
            "latitude": float(item["address"]["geo"]["lat"]),
            "longitude": float(item["address"]["geo"]["lng"]),
            "company": item["company"]["name"],
            "website": item["website"]
        }
        
        customers_data.append(record)
        
    return customers_data
clean_customers = extract_attributes(customer_info)
clean_customers

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'email_domain': 'april.biz',
  'phone': '1-770-736-8031 x56442',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'latitude': -37.3159,
  'longitude': 81.1496,
  'company': 'Romaguera-Crona',
  'website': 'hildegard.org'},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'email_domain': 'melissa.tv',
  'phone': '010-692-6593 x09125',
  'city': 'Wisokyburgh',
  'zipcode': '90566-7771',
  'latitude': -43.9509,
  'longitude': -34.4618,
  'company': 'Deckow-Crist',
  'website': 'anastasia.net'},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'email_domain': 'yesenia.net',
  'phone': '1-463-123-4447',
  'city': 'McKenziehaven',
  'zipcode': '59590-4157',
  'latitude': -68.6102,
  'longitude': -47.0653,
  'company': 'Romaguera-Jacobson',
  'website': 'ramiro.info'},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'email_domain': 'kory.org',
  'phone': '493-170-9623 x156',
  'city': 'South Elvis',
  'zipcode': '53919-4257',
  'latitude': 29.4572,
  'longitude': -164.299,
  'company': 'Robel-Corkery',
  'website': 'kale.biz'},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'email_domain': 'annie.ca',
  'phone': '(254)954-1289',
  'city': 'Roscoeview',
  'zipcode': '33263',
  'latitude': -31.8129,
  'longitude': 62.5342,
  'company': 'Keebler LLC',
  'website': 'demarco.info'},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'email_domain': 'jasper.info',
  'phone': '1-477-935-8478 x6430',
  'city': 'South Christy',
  'zipcode': '23505-1337',
  'latitude': -71.4197,
  'longitude': 71.7478,
  'company': 'Considine-Lockman',
  'website': 'ola.org'},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'email_domain': 'billy.biz',
  'phone': '210.067.6132',
  'city': 'Howemouth',
  'zipcode': '58804-1099',
  'latitude': 24.8918,
  'longitude': 21.8984,
  'company': 'Johns Group',
  'website': 'elvis.io'},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'email_domain': 'rosamond.me',
  'phone': '586.493.6943 x140',
  'city': 'Aliyaview',
  'zipcode': '45169',
  'latitude': -14.399,
  'longitude': -120.7677,
  'company': 'Abernathy Group',
  'website': 'jacynthe.com'},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'email_domain': 'dana.io',
  'phone': '(775)976-6794 x41206',
  'city': 'Bartholomebury',
  'zipcode': '76495-3109',
  'latitude': 24.6463,
  'longitude': -168.8889,
  'company': 'Yost and Sons',
  'website': 'conrad.com'},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'email_domain': 'karina.biz',
  'phone': '024-648-3804',
  'city': 'Lebsackbury',
  'zipcode': '31428-2261',
  'latitude': -38.2386,
  'longitude': 57.2232,
  'company': 'Hoeger LLC',
  'website': 'ambrose.net'}]

Use sets to find unique cities

In [12]:
def unique_cities(customers):
    cities = set()

    for customer in customers:
        cities.add(customer["address"]["city"])

    return cities

city_set = unique_cities(customer_info)
num_customers = len(customer_info)
no_cities = len(city_set)
print(f"Total customers are {num_customers}")
print(f"Total cities are {no_cities}")      
print(f"The total number of customers is {num_customers} and they are locoated in a total of {no_cities} cities. We have equally distributed customers ")

Total customers are 10
Total cities are 10
The total number of customers is 10 and they are locoated in a total of 10 cities. We have equally distributed customers

Count customers by city with loops

In [13]:
def city_counts(customers):
    counts = {}

    for customer in customers:
        city = customer["address"]["city"]
        counts[city] = counts.get(city, 0) + 1

    return counts
city_counts(customer_info)

{'Gwenborough': 1,
 'Wisokyburgh': 1,
 'McKenziehaven': 1,
 'South Elvis': 1,
 'Roscoeview': 1,
 'South Christy': 1,
 'Howemouth': 1,
 'Aliyaview': 1,
 'Bartholomebury': 1,
 'Lebsackbury': 1}

In [14]:
def email_domain_counts(customers):
    domains = {}

    for customer in customers:
        domain = customer["email"].split("@")[1]
        domains[domain] = domains.get(domain, 0) + 1

    return domains
email_domain_counts(customer_info)

{'april.biz': 1,
 'melissa.tv': 1,
 'yesenia.net': 1,
 'kory.org': 1,
 'annie.ca': 1,
 'jasper.info': 1,
 'billy.biz': 1,
 'rosamond.me': 1,
 'dana.io': 1,
 'karina.biz': 1}

Convert the data into a DataFrame and Export the results to CSV

In [15]:
def to_df(data):
    df = pd.DataFrame(data) 
    return df
df_customers = to_df(customer_info)
df_customers

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [16]:
df_customers.to_csv("output/customers.csv", index=False)

In [17]:
city_dict = city_counts(customer_info)
city_dict
df_city_counts = pd.DataFrame(list(city_dict.items()), columns=["city", "count"])
df_city_counts

             city  count
0     Gwenborough      1
1     Wisokyburgh      1
2   McKenziehaven      1
3     South Elvis      1
4      Roscoeview      1
5   South Christy      1
6       Howemouth      1
7       Aliyaview      1
8  Bartholomebury      1
9     Lebsackbury      1

In [18]:
df_city_counts.to_csv("output/city_counts.csv", index=False)

Visualise the customer distribution

In [19]:
def plot_distribution(counts_dict, path):
   
    categories = list(counts_dict.keys())
    values = list(counts_dict.values())
    
    
    plt.figure(figsize=(10, 5))
    
  
    plt.bar(categories, values, color='skyblue')
    
    
    plt.xlabel("Categories")
    plt.ylabel("Count")
    plt.title("Pesa Pulse Customer Distribution")
    plt.xticks(rotation=45, ha='right')
    
   
    plt.tight_layout()
    
    
    plt.savefig(path)
    plt.close()
    print(f"Chart successfully saved to {path}")

plot_distribution(city_dict, "output/city_distribution.png")

Chart successfully saved to output/city_distribution.png